CC = gcc  
CFLAGS = -Wall -Wextra -std=c99 -I../include  
  
TARGET = cn_tower_game.exe  
  
SRC_DIR = .  
SRCS = $(wildcard $(SRC_DIR)/*.c)  
  
OBJS = $(SRCS:.c=.o)  
  
all: $(TARGET)  
  
$(TARGET): $(OBJS)  
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)  
  
  
%.o: %.c  
