# src/Makefile

CC = cl
CFLAGS = /W4 /WX
LDFLAGS =

SRCS = $(wildcard *.c)
OBJS = $(SRCS:.c=.obj)

all: cn_tower_game.exe

cn_tower_game.exe: $(OBJS)
	$(CC) $(LDFLAGS) -Fe$@ $^

%.obj: %.c
	$(CC) $(CFLAGS) -c $<

clean:
	del /Q *.obj cn_tower_game.exe
